name:                dbgen
version:             0.1.0.0
github:              "adinapoli-iohk/dbgen"
license:             BSD3
author:              "Alfredo Di Napoli"
maintainer:          "alfredo.dinapoli@iohk.io"
copyright:           "2017-2018 Alfredo Di Napoli"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/dbgen#readme>

dependencies:
- base >= 4.7 && < 5
- dhall
- text
- time
- QuickCheck
- bytestring
- string-conv
- lens
- haskoin-core
- cardano-sl
- cardano-sl-core
- cardano-sl-db
- cardano-sl-ssc
- cardano-sl-infra
- cardano-sl-wallet

library:
  source-dirs: src
  default-extensions:
    OverloadedStrings
    RecordWildCards

executables:
  dbgen:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - dbgen
    - optparse-generic
    - optparse-applicative
    - node-sketch
    - mtl
    - log-warper
    - data-default
    - lens
    default-extensions:
      RecordWildCards
      OverloadedStrings
